name: publish-edge
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.run/**'
      - 'charts/**'
      - '.*'
      - 'README.md'
      - 'Taskfile.*'
      - 'version.go'

jobs:
  publish-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          pull: true
          push: true
          tags: roeldev/youless-observer:edge
